### ISSUE TITLE
this looks like a good idea but is it doing anything?

### ISSUE THREAD

**Issue by okurz** [zoffixznet/Mojolicious-Plugin-IRCBot#1]

**Comment by zoffixznet** [comment]
There are no docs, specs, or non-boilerplate code, mate. I'm unsure what made you think something was a "good idea." If you wish to claim the namespace, go right ahead. It's unlikely I'll follow through with the actual idea I had, as there are some unresolvable architecture issues that would severely limit usefulness of the plugin.
